### ISSUE TITLE
Update check

### ISSUE THREAD

**Issue by Rintan** [Meshida/DataManagementRepositoryForMumeiServer#1]
いつもお世話になっています。

新機能の提案ですが、このレポジトリを利用して、アプリの更新を確認できるようにしてはどうでしょうか。
アプリの最新のバージョンが記載されたファイルを置いておき、クライアントのバージョンと比較して違った場合に他に用意したアップデート情報のファイルを読み込ませるというものを想定しています。
オープンソースではないので、直接協力できず申し訳ありません。ご検討よろしくお願いします。

**Comment by GenbuHase** [comment]
横から失礼致します。
それでしたら私も協力出来そうです。

**Comment by Meshida** [comment]
ご提案ありがとうございます。
こちらとしましても、そういった機能の追加を考えていましたので実装させていただきます。
また、質問なのですが、

**Comment by Meshida** [comment]
(途切れた)
Web上のテキストファイルを表示する方法が分かりません(メインスレッド以外で動かす方法です)。
可能でありましたらご教授願います。

**Comment by GenbuHase** [comment]
@Meshida 
それでしたら新しくThread建てるだけで可能ですよ。

**Comment by Meshida** [comment]
あっ...
了解です
